sudo: required

language: python
python: "3.5"

services:
    - docker

install: "pip install -r requirements.txt"

before_script:
      - sudo /etc/init.d/mysql stop

script:
    #- docker-compose up
    - exit 1
