version: '3'

services:
    sql_root:
        image: mysql
        volumes:
            - ./private/data/${INSTANCE}:/data
        env_file:
            - ./private/conf/${INSTANCE}/learnball_sql.env
        ports:
            - "3306:3306"
        healthcheck:
            # figure out how to inject "create users for other services" into this healthcheck
            test: ["CMD", "mysql", "--version"]
            interval: 10s
            timeout: 2s
            retries: 6

    tg_records:
        build: ./tg_records
        command: python3 /code/manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        depends_on:
            - sql_root
        env_file:
            - ./private/conf/${INSTANCE}/tg_records.env
            - ./private/conf/${INSTANCE}/learnball_sql.env
        volumes:
            - ./tg_records:/code
        links:
            - sql_root
